name: Auto Moonsec Deobfuscator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deobfuscate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Pembersihan & Reformat Kode Raksasa (Python Token Fix)
      run: |
        python -c "
        with open('w.txt', 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        # 1. Bersihkan junk code tulisan protected di paling awal
        start_idx = content.find('return(function')
        if start_idx != -1:
            content = content[start_idx:]
        
        # 2. Pecah baris raksasa berdasarkan delimiter Lua agar ANTLR Parser tidak muntah
        # Kita tambahkan newline setelah ';', 'then', 'do', 'else', dan 'end '
        content = content.replace(';', ';\n')
        content = content.replace('then', 'then\n')
        content = content.replace('do', 'do\n')
        content = content.replace('else', '\nelse\n')
        content = content.replace('end', '\nend\n')
        
        with open('w.txt', 'w', encoding='utf-8') as f:
            f.write(content)
        print('[-] BERHASIL: File w.txt berhasil dipecah menjadi multi-line rapi.')
        "
        echo "=== LIHAT 10 BARIS PERTAMA HASIL REFORMAT ==="
        head -n 10 w.txt
        echo "============================================="

    - name: Restore Dependencies
      run: dotnet restore MoonsecDeobfuscator.csproj

    - name: Jalankan Deobfuscator
      run: |
        dotnet run --project MoonsecDeobfuscator.csproj -c Release -- -dev -i w.txt -o hasil_bongkar.luac

    - name: Upload Hasil Bongkar
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Bongkar-Moonsec
        path: hasil_bongkar.luac
