name: Auto Moonsec Deobfuscator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deobfuscate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore MoonsecDeobfuscator.csproj

    - name: Pembersihan junk code MoonSec V3 (Pre-Processing Aman)
      run: |
        # Menggunakan sed dengan pola yang sangat ketat hanya menghapus bagian pembuka gsub di baris awal
        sed -i "s/([[This file was protected with MoonSec V3]]):gsub('.+', (function(a) __xirluziHIZB = a; end)); //" w.txt
        
        echo "=== CEK 150 KARAKTER PERTAMA W.TXT ==="
        head -c 150 w.txt
        echo -e "\n======================================="

    - name: Jalankan Deobfuscator (Bypass Compiler Warning)
      run: |
        dotnet run --project MoonsecDeobfuscator.csproj -c Release --property:WarningLevel=0 -- -dev -i w.txt -o hasil_bongkar.luac

    - name: Upload Hasil Bongkar
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Bongkar-Moonsec
        path: hasil_bongkar.luac
