name: Auto Moonsec Deobfuscator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deobfuscate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Pembersihan Junk Code MoonSec Teliti (Python Clean)
      run: |
        python -c "
        with open('w.txt', 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        # Cari titik awal murni dari fungsi return MoonSec
        start_idx = content.find('return(function')
        if start_idx != -1:
            clean_content = content[start_idx:]
            # Tulis ulang file rapet di baris 1 tanpa spasi/newline ampas
            with open('w.txt', 'w', encoding='utf-8') as f:
                f.write(clean_content)
            print('[-] BERHASIL: File w.txt dibersihkan dengan presisi.')
        else:
            print('[-] PERINGATAN: return(function tidak ditemukan, file tidak diubah.')
        "
        echo "=== TAMPILAN 120 KARAKTER PERTAMA W.TXT ==="
        head -c 120 w.txt
        echo -e "\n=========================================="

    - name: Restore Dependencies
      run: dotnet restore MoonsecDeobfuscator.csproj

    - name: Jalankan Deobfuscator
      run: |
        dotnet run --project MoonsecDeobfuscator.csproj -c Release --property:WarningLevel=0 -- -dev -i w.txt -o hasil_bongkar.luac

    - name: Upload Hasil Bongkar
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Bongkar-Moonsec
        path: hasil_bongkar.luac
